---
swagger: "2.0"
info:
  description: "Google Compute Engine Instance using -2.0 specification and codegen"
  version: "0.0.1"
  title: "gce_vm_info"
  termsOfService: "http://swagger.io/terms/"
  contact:
    name: "Bertolt Sobolik"
  license:
    name: "Apache"
host: "localhost:8080"
basePath: "/api"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /vms:
    get:
      description: "Returns a list of VMs"
      operationId: "vms_get"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "VM instance"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/VM"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /vms/{id}:
    get:
      description: "Returns information on a VM instance"
      operationId: "vms_id_get"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "VM instance"
          schema:
            $ref: "#/definitions/VM"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /vms/{id}/disks/:
    get:
      description: "Returns a list of disks attached to a VM"
      operationId: "vms_id_disks_get"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Disk"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/DISK"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  VM:
    type: "object"
    properties:
      id:
        type: "string"
      creationTimestamp:
        type: "string"
        format: "date-time"
      name:
        type: "string"
      description:
        type: "string"
      tags:
        $ref: "#/definitions/VM_tags"
      machineType:
        type: "string"
      status:
        type: "string"
        enum:
        - "PROVISIONING"
        - "STAGING"
        - "RUNNING"
        - "STOPPING"
        - "STOPPED"
        - "SUSPENDING"
        - "SUSPENDED"
        - "TERMINATED"
      canIpForward:
        type: "boolean"
      cpuPlatform:
        type: "string"
      deletionProtection:
        type: "boolean"
      disks:
        type: "array"
        items:
          $ref: "#/definition/DISK"
      kind:
        type: "string"
      labelFingerprint:
        type: "string"
    example:
      canIpForward: true
      disks:
      - autoDelete: true
        guestOsFeatures:
        - "{}"
        - "{}"
        boot: true
        deviceName: "deviceName"
      - autoDelete: true
        guestOsFeatures:
        - "{}"
        - "{}"
        boot: true
        deviceName: "deviceName"
      kind: "kind"
      description: "description"
      cpuPlatform: "cpuPlatform"
      labelFingerprint: "labelFingerprint"
      tags:
        fingerprint: "fingerprint"
        items:
        - "items"
        - "items"
      deletionProtection: true
      creationTimestamp: "2000-01-23T04:56:07.000+00:00"
      name: "name"
      id: "id"
      machineType: "machineType"
      status: "PROVISIONING"
  DISK:
    type: "object"
    properties:
      autoDelete:
        type: "boolean"
      boot:
        type: "boolean"
      deviceName:
        type: "string"
      guestOsFeatures:
        type: "array"
        items:
          type: "object"
          properties: {}
    example:
      autoDelete: true
      guestOsFeatures:
      - "{}"
      - "{}"
      boot: true
      deviceName: "deviceName"
  VM_tags:
    properties:
      items:
        type: "array"
        items:
          type: "string"
      fingerprint:
        type: "string"
        format: "byte"
        pattern: "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$"
        x-regex: "^(?:[A-Za-z0-9+\\/]{4})*(?:[A-Za-z0-9+\\/]{2}==|[A-Za-z0-9+\\/]{3}=)?$"
        x-modifiers: []
    example:
      fingerprint: "fingerprint"
      items:
      - "items"
      - "items"
